### ISSUE TITLE
How to participate in your organization's workshop online

### ISSUE THREAD

**Issue by Navi0116** [coperception/.github#1]
I am highly interested in your organization's workshop titled "CoPerception: Collaborative Perception and Learning". However, I am unable to attend the workshop in person. I would greatly appreciate it if you could provide me with information on how to participate in this workshop online. Thank you very much.

**Comment by simbaforrest** [comment]
Thank you. We will post the Zoom link on our LinkedIn post (https://www.linkedin.com/feed/update/urn:li:activity:7069319046759886849/) and the workshop website before the workshop.

We will also post the recording on youtube later.

**Comment by simbaforrest** [comment]
@Navi0116 Here is the zoom link: https://us06web.zoom.us/j/83369956628?pwd=TG82bUd0RTArYThFWXpYd3h6RGk4Zz09

**Comment by Navi0116** [comment]
Thank you for your generous sharing!

**Comment by simbaforrest** [comment]
Welcome to this rising field of research ;-)
